### ISSUE TITLE
How to set fontfamily?

### ISSUE THREAD

**Issue by nolife08021** [jsamr/react-native-render-html-table-bridge#13]
It pop "Unrecognized font family 'DengXian'" error, how can i set in style that all will use as fontFamily:system ?
Or is that anyway to ignore the font-family style?

I have tried set `baseFontStyle={{ fontFamily:"System" }}` but same error shows out.

`"<p><span style=\"font-family:DengXian; font-size:15.0pt\">testing</span></p>"
`

**Comment by jsamr** [comment]
@nolife08021 To use custom fonts, you need to ship them with your app. [Read this thread for more information](https://github.com/react-native-community/react-native-webview/issues/326#issuecomment-510005798).

**Comment by donni106** [comment]
> 
> 
> @nolife08021 To use custom fonts, you need to ship them with your app. [Read this thread for more information](https://github.com/react-native-community/react-native-webview/issues/326#issuecomment-510005798).

should this work with expo and version 2.1.5? i am not able to make my custom font work.
