### ISSUE TITLE
How to add cellspacing style of Table View?

### ISSUE THREAD

**Issue by sunilprajapati714** [jsamr/react-native-render-html-table-bridge#15]
I'm able to add cellpadding using `cellPaddingEm` in tableview.

How can I add cellspacing in tableview?

Want tableview like this screen shot 👇🏻
![Screenshot 2020-05-07 at 12 24 29 PM](https://user-images.githubusercontent.com/29479459/81263677-bb7b4e00-905d-11ea-8eca-2fa2801c03d3.png)

**Comment by jsamr** [comment]
@sunilprajapati714 You can use the [border-spacing](https://www.w3schools.com/cssref/pr_border-spacing.asp) css attribute. Pass css with the [`cssRules` config](https://github.com/jsamr/react-native-render-html-table-bridge#how-to-extend-default-or-custom-styles).

**Comment by sunilprajapati714** [comment]
```
import { defaultTableStylesSpecs, cssRulesFromSpecs } from 'react-native-render-html-table-bridge';

const cssRules = cssRulesFromSpecs(defaultTableStylesSpecs) + `
table {
    border-spacing:  2px 2px
}`

const config = {
    WebViewComponent: WebView,
    tableStyleSpecs: { //This tableStyleSpecs will no more work
        cellPaddingEm: 0.25,
        borderWidthPx: 0.25,
        thBorderColor: 'black',
        tdBorderColor: 'black',
        thOddBackground: 'white',
        thEvenBackground: 'white',
        trOddBackground: 'white',
        trEvenBackground: 'white',
    },
    cssRules,
    webViewProps: {
        showsVerticalScrollIndicator: false,
        showsHorizontalScrollIndicator: false,
    }
};
```

This `tableStyleSpecs` will no more work if pass css with the **cssRules config**.
