### ISSUE TITLE
HTML.onLinkPress does not get fired if link contains html elements

### ISSUE THREAD

**Issue by janrop** [jsamr/react-native-render-html-table-bridge#5]
Hi there,

I noticed a bug which causes the onLinkPress method to not be fired.

If there is an anchor element inside a table which itself contains more markup (i.E. an img or an i-tag), the onLinkPress method does not fire.

    "react-native-render-html": "4.1.2",
    "react-native-render-html-table-bridge": "0.4.0-rc.1",
    "react-native-webview": "5.12.1",

HTML to reproduce:

    <table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
    <tr>
    <td style="width: 50%;">Test <a href="http://text:189">[info]</a></td>
    <td style="width: 50%;">Test <a href="http://text:189"><sup>[info]</sup></a></td>
    </tr>
    </tbody>
    </table>

**Comment by jsamr** [comment]
@janrop I could reproduce. Investigating.
