### ISSUE TITLE
Is there a way to apply styles to the WebView?

### ISSUE THREAD

**Issue by mllngtn** [jsamr/react-native-render-html-table-bridge#6]
Hi,

A mysterious black 'border' is showing at the bottom of my WebView on iOS: ![Screen Shot 2019-09-13 at 11 20 30 AM](https://user-images.githubusercontent.com/988313/64827514-9b070b00-d618-11e9-92c6-391c4ca9fda9.png)

It looks like this is a known issue with react-native-webview - the fix is to specify a transparent background color for the WebView: https://stackoverflow.com/questions/41188362/react-native-webview-rendering-unexpected-border-at-bottom

My question is: is there any way to add styles to the WebView component using this module (I can obviously apply styles to the table, but can't figure out how to make changes to the WebView itself)? 

Thanks!

**Comment by jsamr** [comment]
@mllngtn Have you tried with [`webviewProps`](https://github.com/jsamr/react-native-render-html-table-bridge#webviewprops)? You should be able to pass a `style` prop through it.

**Comment by mllngtn** [comment]
@jsamr Thank you! I am a fool and somehow skipped over that section of the docs
