### ISSUE TITLE
Android scroll conflict

### ISSUE THREAD

**Issue by Runtime007** [jsamr/react-native-render-html-table-bridge#9]
In Android, if Html in ScrollView and table's columns > 2, it's not easy to scroll table to the left to show other columns. iOS is OK.
```js
<ScrollView>
    <HTML
         {...htmlConfig}
         html={html}
    />
</ScorllView>
```
![image](https://user-images.githubusercontent.com/5061166/72312326-c0894b80-36c2-11ea-9c91-2706d860ded0.png)

**Comment by jsamr** [comment]
@Runtime007 To help you, I will need you to produce a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), in the form of an expo snack or git repository. Also, I am not sure about the issue!

**Comment by Runtime007** [comment]
[here ](https://github.com/Runtime007/test4htmlrenderbidge.git)is the code. ` Android 9.0 Galaxy s9+`. I try to scroll the table to left or right, but the ScrollView captured the move event and it scrolls down or up, there is no response for the table sometimes.

**Comment by Runtime007** [comment]
hi, @jsamr, this issue has troubled me several days. I try to fix it by setting `PanResponder` for webview and listening to touch events to avoid scroll conflict but come to nothing. So I have to change android source code for react-native-webview, and it works.
```java
    float startX = 0;
    float startY = 0;
    float dx = 0;
    float dy = 0;
    @Override
    public boolean onTouchEvent(MotionEvent event){
      switch (event.getAction()) {
        case MotionEvent.ACTION_DOWN:
          getParent().requestDisallowInterceptTouchEvent(true);
          startX = event.getX();
          startY = event.getY();
          break;
        case MotionEvent.ACTION_MOVE:
          dx = Math.abs(event.getX() - startX);
          dy = Math.abs(event.getY() - startY);
          if (dx > dy) {
            getParent().requestDisallowInterceptTouchEvent(true);
          } else {
            getParent().requestDisallowInterceptTouchEvent(false);
          }
          break;
      }

      return super.onTouchEvent(event);
    }
    ....
```

**Comment by jsamr** [comment]
@Runtime007 I'll take a look today!

**Comment by jsamr** [comment]
@Runtime007 The issue is that you would like a minimum dy value for the gesture to trigger a scroll event in the root ScrollView component. Something like the `activeOffsetY` prop from [RNGH `PanGestureHandler`](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pan.html#activeoffsety)

I see two options : 

1. [Get inspiration from this hacking](https://medium.com/@contact_27678/one-way-to-properly-manage-nested-scrollviews-in-react-native-ae837296d199).
2. Render table previews and offer full table layout in a separate modal or screen after user press.

In either cases, you will need [`makeCustomTableRenderer`](https://github.com/jsamr/react-native-render-html-table-bridge#how-to-customize-the-table-component).

I hope you'll find something workable. I will close because this limitation is broadly from react-native. But if you dig any workaround, please post your findings!

Best,

JSR

**Comment by jsamr** [comment]
> hi, @jsamr, this issue has troubled me several days. I try to fix it by setting `PanResponder` for webview and listening to touch events to avoid scroll conflict but come to nothing. So I have to change android source code for `react-native-webview`, and it works.
> 
> ```java
> protected static class RNCWebView extends WebView implements LifecycleEventListener {
>     ...
> 
>     float startX = 0;
>     float startY = 0;
>     float dx = 0;
>     float dy = 0;
> 
>     @Override
>     public boolean onTouchEvent(MotionEvent event){
>       switch (event.getAction()) {
>         case MotionEvent.ACTION_DOWN:
>           getParent().requestDisallowInterceptTouchEvent(true);
>           startX = event.getX();
>           startY = event.getY();
>           break;
>         case MotionEvent.ACTION_MOVE:
>           dx = Math.abs(event.getX() - startX);
>           dy = Math.abs(event.getY() - startY);
>           if (dx > dy) {
>             getParent().requestDisallowInterceptTouchEvent(true);
>           } else {
>             getParent().requestDisallowInterceptTouchEvent(false);
>           }
>           break;
>       }
> 
>       return super.onTouchEvent(event);
>     }
>     ...
> 
> }
> ```

Third option : I would suggest you offer a PR to `react-native-webview` with a prop enabling the behavior you have implemented. Not sure about the best chose of words though!

**Comment by Runtime007** [comment]
> @Runtime007 The issue is that you would like a minimum dy value for the gesture to trigger a scroll event in the root ScrollView component. Something like the `activeOffsetY` prop from [RNGH `PanGestureHandler`](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pan.html#activeoffsety)
> 
> I see two options :
> 
> 1. [Get inspiration from this hacking](https://medium.com/@contact_27678/one-way-to-properly-manage-nested-scrollviews-in-react-native-ae837296d199).
> 2. Render table previews and offer full table layout in a separate modal or screen after user interaction.
> 
> In either cases, you will need [`makeCustomTableRenderer`](https://github.com/jsamr/react-native-render-html-table-bridge#how-to-customize-the-table-component).
> 
> I hope you'll find something workable. I will close because this limitation is broadly from react-native. But if you dig any workaround, please post your findings!
> 
> Best,
> 
> JSR

Thank you very much for your proposals, I'll check and try, to see if it can be implemented on the react side.

Best regards.

**Comment by chr314** [comment]
#14 merged, now you can use onMessage and injectedJavaScript webview props

you can disable scroll of ScrollView with scrollEnabled prop

```jsx
<ScrollView scrollEnabled={this.state.scrollEnabled}>
          <HTML
            alterNode={alterNode}
            renderers={this.htmlRenderers}
            ignoredTags={IGNORED_TAGS}
            html={this.state.content}
          />
</ScrollView>
```

```js
  scrollTimer;
  onTableMessage = (event) => {
    if (event.data === 'scroll') {
      if (this.scrollTimer) {
        clearTimeout(this.scrollTimer);
      }
      this.setState({scrollEnabled: false}, () => {
        this.scrollTimer = setTimeout(() => {
          this.setState({scrollEnabled: true});
        }, 100);
      });
    }
  };

  htmlRenderers = {
    table: makeTableRenderer({
      WebViewComponent: WebView,
      webViewProps: {
        onMessage: this.onTableMessage,
        injectedJavaScript:
          "setTimeout(() => {document.addEventListener('scroll', function () {window.ReactNativeWebView.postMessage('scroll');},true);}, 300);",
      },
    }),
  };
```
